services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: edensit139/whatsy:backend-dev
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - BASE_URL=http://dev.whatsy:5000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: edensit139/whatsy:frontend-dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://dev.whatsy:5000
    depends_on:
      - backend